package pmml;

import java.util.List;

/**
 * Created by yu_wei on 2018/6/11.
 */
public class DataBean {

    public List<String> keys;
    public float[] data;

    static final String[] featureList = {
            "cr",
            "delta_hotel_city_price",
            "delta_hotel_self_price",
            "delta_hotel_zone_price",
            "dynamic_price_down",
            "fh_price_block_100_1",
            "fh_price_block_100_11",
            "fh_price_block_100_12",
            "fh_price_block_100_2",
            "fh_price_block_100_3",
            "fh_price_block_100_4",
            "fh_price_block_100_5",
            "fh_price_block_100_6",
            "fh_price_block_100_7",
            "fh_price_block_100_8",
            "fh_price_block_100_9",
            "fh_price_block_200_1",
            "fh_price_block_200_2",
            "fh_price_block_200_3",
            "fh_price_block_200_4",
            "fh_price_block_200_5",
            "fh_price_block_200_6",
            "fh_price_block_200_7",
            "fh_price_quantile_1",
            "fh_price_quantile_2",
            "fh_price_quantile_3",
            "fh_price_quantile_4",
            "fh_price_quantile_5",
            "hotel_avg_picturerank",
            "hotel_brand_cr_mean",
            "hotel_brand_hotel_order_cnt_7d_mean",
            "hotel_brand_hotel_uv_list_avg_7d_mean",
            "hotel_ciireceivable_sum_7d",
            "hotel_ctr_is_dist_qry_0",
            "hotel_ctr_is_dist_qry_1",
            "hotel_ctr_is_price_qry_1",
            "hotel_ctr_total",
            "hotel_fh_price_avg_7d",
            "hotel_fitmentyear_diffdays",
            "hotel_fromairport_block_1",
            "hotel_fromairport_block_2",
            "hotel_fromairport_block_3",
            "hotel_fromairport_block_4",
            "hotel_fromairport_block_5",
            "hotel_fromairport_block_6",
            "hotel_fromairport_quantile_1",
            "hotel_fromairport_quantile_2",
            "hotel_fromairport_quantile_3",
            "hotel_fromairport_quantile_4",
            "hotel_fromairport_quantile_5",
            "hotel_fromcitycenter_block_1",
            "hotel_fromcitycenter_block_2",
            "hotel_fromcitycenter_block_3",
            "hotel_fromcitycenter_block_4",
            "hotel_fromcitycenter_block_5",
            "hotel_fromcitycenter_block_6",
            "hotel_fromcitycenter_quantile_1",
            "hotel_fromcitycenter_quantile_2",
            "hotel_fromcitycenter_quantile_3",
            "hotel_fromcitycenter_quantile_4",
            "hotel_fromcitycenter_quantile_5",
            "hotel_fromtrain_block_1",
            "hotel_fromtrain_block_2",
            "hotel_fromtrain_block_3",
            "hotel_fromtrain_block_4",
            "hotel_fromtrain_block_5",
            "hotel_fromtrain_block_6",
            "hotel_fromtrain_quantile_1",
            "hotel_fromtrain_quantile_2",
            "hotel_fromtrain_quantile_3",
            "hotel_fromtrain_quantile_4",
            "hotel_fromtrain_quantile_5",
            "hotel_goldstar_0",
            "hotel_goldstar_1",
            "hotel_goldstar_2",
            "hotel_goldstar_3",
            "hotel_goldstar_4",
            "hotel_goldstar_5",
            "hotel_goldstar_6",
            "hotel_mainscore",
            "hotel_novoters",
            "hotel_order_cnt_7d",
            "hotel_order_ratio_zone",
            "hotel_pv_list_avg_7d",
            "hotel_score",
            "hotel_star_0",
            "hotel_star_1",
            "hotel_star_2",
            "hotel_star_3",
            "hotel_star_4",
            "hotel_star_5",
            "hotel_tag_20_30",
            "hotel_tag_60_on",
            "hotel_tag_xiuxiandujia_r",
            "hotel_uv_list_avg_7d",
            "hotel_uv_ratio_zone",
            "hotel_zone_avg_order_cnt_31d",
            "hotel_zone_avg_order_cnt_7d",
            "hotel_zone_cr_mean",
            "hotel_zone_hotel_order_cnt_7d_mean",
            "hotel_zone_hotel_uv_list_avg_7d_mean"
    };
}
